/*#define BSAS_EVENT_POWER	0
	#define BSAS_EVENTVALUE_POWER_ON	1
	#define BSAS_EVENTVALUE_POWER_OFF	2*/

#define _AS_BSAS_PREFIX			"BSAS\\"
#define BSAS_EVENT_OUT_CONSOLE	_AS_BSAS_PREFIX "ConsoleOut"
#define BSAS_EVENT_OUT_DISPLAY	_AS_BSAS_PREFIX "DisplayOut"
#define BSAS_EVENT_OUT_SPEAKER	_AS_BSAS_PREFIX "SpeakerOut"

// Common Events
#define BSAS_EVENT_VALUE_POWER_ON	1
#define BSAS_EVENT_VALUE_POWER_OFF	2
#define BSAS_EVENT_VALUE_TEXT		3
#define BSAS_EVENT_VALUE_CONFIRMED	4
#define BSAS_EVENT_VALUE_STOP		5

// Display Events
#define BSAS_EVENT_VALUE_INTENSITY	100

// Sound Evants
#define BSAS_EVENT_VALUE_PLAYAUDIO	100
#define BSAS_EVENT_VALUE_SETVOLUME	101

#define BSAS_EVENT_RESULT_OK		0
#define BSAS_EVENT_RESULT_NOT_IMPL	1
#define BSAS_EVENT_RESULT_NOT_FOUND	2

#define AS_BSASLT_COMMAND	_AS_BSAS_PREFIX "Command"
#define BSASLT_CMD_POWER		0
#define BSASLT_CMD_D1			1
#define BSASLT_CMD_D2			2
#define BSASLT_CMD_D3			3
#define BSASLT_CMD_D4			4
#define BSASLT_CMD_D5			5
#define BSASLT_CMD_D6			6
#define BSASLT_CMD_D7			7
#define BSASLT_CMD_U1			11
#define BSASLT_CMD_U2			12
#define BSASLT_CMD_U3			13
#define BSASLT_CMD_U4			14
#define BSASLT_CMD_U5			15
#define BSASLT_CMD_U6			16
#define BSASLT_CMD_U7			17
#define BSASLT_CMD_L1			21
#define BSASLT_CMD_L2			22
#define BSASLT_CMD_L3			23
#define BSASLT_CMD_L4			24
#define BSASLT_CMD_L5			25
#define BSASLT_CMD_L6			26
#define BSASLT_CMD_L7			27

#define BSASLT_CMD_U_SLOT		100
#define BSASLT_CMD_U_PRECOPY	101
#define BSASLT_CMD_U_COPY		111
#define BSASLT_CMD_U_PRECLEAR	102
#define BSASLT_CMD_U_CLEAR		112
#define BSASLT_CMD_U_INTENSITY	103
#define BSASLT_CMD_U_SEND		104
#define BSASLT_CMD_U_CONFIRM	105
#define BSASLT_CMD_U_DATE		106

#define BSASLT_CMD_R_RESET		200
#define BSASLT_CMD_R_SIDE		201
#define BSASLT_CMD_R_VOLUME		202
#define BSASLT_CMD_R_SKIP		203
#define BSASLT_CMD_R_REPEAT		204
#define BSASLT_CMD_R_STOP		205
#define BSASLT_CMD_R_PLAY		206

#define BSASLT_CMD_R_CUSTOM1	300
#define BSASLT_CMD_R_CUSTOM2	301
#define BSASLT_CMD_R_CUSTOM3	302
#define BSASLT_CMD_R_CUSTOM4	303
#define BSASLT_CMD_R_CUSTOM5	304
#define BSASLT_CMD_R_CUSTOM6	305
#define BSASLT_CMD_R_CUSTOM7	306

#define BSASLT_CMD_S_CUSTOMPLAY	400
#define BSASLT_CMD_S_LOADZIP	401

#define BSASLT_RETURN_OK		0
#define BSASLT_RETURN_STATE		1
